cm : 
	gcc -o Tick Tick.c
	gcc -o cmd_sel cmd_sel.c
	gcc -o server server.c
	gcc -o Display Display.c
	gcc -o Main Main.c
cln : 
	rm current_state.dat
	rm time_check_file.dat
	rm sensor.dat
	rm tick.dat
	rm overall_data.dat
	rm reserve.dat
